# Generated by Django 4.2.4 on 2023-08-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Advert', '0005_alter_advertisement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
    ]
