# Generated by Django 4.2.4 on 2023-08-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Advert', '0006_remove_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='Advert/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
