# Generated by Django 4.2.4 on 2023-08-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Advert', '0007_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='advertisement/', verbose_name='изображение'),
        ),
    ]
